version: '3'
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - CHAT_DSN=mongodb://mongodb:27017/chat
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 8333:8333
        links:
            - mongodb
        command: "node app.js"

    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod
